import Link from 'next/link';
import { PageHeader } from '@/components/PageHeader';
import { DownloadIcon } from '@/components/Brand';
import { downloadHref, localDownloadsEnabled, release } from '@/lib/content';
export const metadata = { title: 'Learn' };
export const dynamic = 'force-dynamic';
export default function Learn() {
  const local = localDownloadsEnabled();
  const published = release.publication.status === 'published';
  return <><PageHeader /><main className="reading"><div className="intro"><p className="eyebrow">Meet Zero</p><h1>Make something with Java.</h1><p className="lead">Edit ordinary Java in VS Code. Run your app in its own JavaFX window.</p></div>
    <section><h2>A small kit, room to grow</h2><p>Start with a quiz, then build an interface, a drawing, a game or a simulation. Zero includes a VS Code extension, a ready-to-open starter, an optional settings profile and a setup guide. VS Code and the JDK are separate prerequisites.</p><p><code>SimpleApp</code> builds ordinary JavaFX interfaces. <code>SketchApp</code> adds a canvas: your Main explicitly updates and draws your own objects. Readable framework source travels with the starter.</p><figure><img src="/generated/editor.jpg" alt="Zero in VS Code with the app source and minimal Run App sidebar" width="2880" height="1800" /><figcaption>A recorded Zero editor preview. The current kit also includes the individual GitHub workflow.</figcaption></figure></section>
    <section id="downloads"><h2>Get Zero</h2>{published ? <p>Zero {release.kitVersion} is available as a verified, versioned release.</p> : local ? <p>This local preview offers the packaged Zero {release.kitVersion} kit. Downloads are checked against the local release receipt; this version has not been publicly released.</p> : <p>Zero {release.kitVersion} is being prepared locally. A public kit download is not available yet. This page will link to verified release files when publication is complete.</p>}
      {(published || local) && <a className="button primary compact" href={downloadHref()}><DownloadIcon />Download Zero {release.kitVersion}</a>}
      <details><summary>Other downloads</summary>{(published || local) ? <ul>{['starter', 'extension'].map(key => <li key={key}><a href={downloadHref(key)}>{release.assets[key].label}</a></li>)}</ul> : <p>The starter and extension will be available separately with the published kit.</p>}<p><a href="https://github.com/codepetca/zero/releases">Previous releases on GitHub</a></p></details>
    </section>
    <section id="setup"><h2>Your first app</h2><ol className="steps"><li><h3>Install the prerequisites</h3><p>Install <a href="https://code.visualstudio.com/download">VS Code</a> and a supported JDK 17 or later. Check <code>java -version</code> and <code>javac -version</code> in a new terminal, then restart VS Code. JDK 17 was tested; Java editor extensions may need a newer editor JDK.</p></li><li><h3>Extract the kit once</h3><p>Extract the Zero ZIP into your own folder outside any other Git repository. Inside are <code>starter/</code>, the extension VSIX, optional profile and setup guide. Keep hidden <code>.mvn</code> and <code>.vscode</code> folders.</p></li><li><h3>Set up the editor</h3><p>If you want the optional Zero profile, import it first. In that profile, choose <strong>Extensions → Install from VSIX…</strong> and select <code>{release.assets.extension.filename}</code>. Install <strong>Language Support for Java by Red Hat</strong> and <strong>Debugger for Java</strong> too.</p></li><li><h3>Open the starter and run</h3><p>Open the <code>starter/</code> folder in VS Code. Trust it after checking its source and build scripts. Choose <strong>Zero: Show Sidebar</strong>, then <strong>Run App</strong>. First run needs internet to download Maven and JavaFX; students need no Node.js or global Maven.</p></li></ol><p>Edit <code>src/main/java/Main.java</code>, then Run App again to rebuild and restart. <strong>Stop</strong> ends the app. Compiler errors appear in the task terminal and Problems panel. On macOS/Linux, lost ZIP permissions may need <code>chmod +x mvnw</code>.</p><p><Link href="/docs/setup">Full setup and GitHub guide</Link> · <Link href="/docs/starter">Starter guide</Link> · <Link href="/docs/pilot">Classroom pilot checklist</Link></p></section>
    <section><h2>Read, try, change</h2><div className="resource-links"><Link href="/docs/api">Java API reference</Link><Link href="/docs/exercises">Starter exercises</Link><Link href="/docs/product">How Zero works</Link><a href="https://github.com/codepetca/zero">Zero source on GitHub</a></div><p>The API and guides here are prepared from the maintained repository files. Cloning the Zero source repository is for developing Zero; start your own app from the downloaded starter.</p></section>
    <section><h2>Save your work on GitHub</h2><p>Local running needs no sign-in. For uploads, install Git 2.31 or newer, set your repository’s commit name and email, and sign in through VS Code’s native GitHub flow. Students own their repositories and submit their repository link separately in Pika.</p><p><strong>Upload, Start and Finish default to simulation.</strong> Nothing is uploaded or changed in Git until you explicitly enable live mode. Follow the <Link href="/docs/setup">complete guide</Link> for the reviewed individual workflow, and check completed work on GitHub before submitting the link.</p></section>
    <section><h2>Build a reusable component</h2><p>The Component Workshop lets you develop an ordinary Java library, preview it and export a contribution packet. This is experimental local tooling; public Maven artifacts and a hosted catalog are not available.</p><p><Link href="/community">Explore Zero Community</Link> · <Link href="/docs/workshop">Workshop guide</Link> · <Link href="/docs/components">Component architecture</Link></p></section>
    <section className="fine-print"><h2>Current status</h2><p>Zero is an experimental teaching kit. Original Zero code uses the MIT license; bundled dependencies retain their own notices. Physical Windows/Linux setup and novice classroom trials remain unverified. <Link href="/docs/verification">Read the verification record</Link> before classroom adoption.</p></section>
  </main></>;
}
